### PR TITLE
use ::T for types in @trace

### PR DESCRIPTION
**Pull request by MasonProtter**
closes https://github.com/MikeInnes/Mjolnir.jl/issues/9

I incremented the version because this is a breaking change.
```julia
using Mjolnir

@trace sin(::Real)

#+RESULTS:
: 1: (%1 :: const(sin), %2 :: Real)
:   %3 = (sin)(%2)
:   return %3
```
```julia
@trace sin(1)

#+RESULTS:
: 1: (%1 :: const(sin), %2 :: const(1))
:   return 0.8414709848078965
```
```julia
@trace sin(::Mjolnir.Const(1))

#+RESULTS:
: 1: (%1 :: const(sin), %2 :: const(1))
:   return 0.8414709848078965
```

### CODE REVIEW

**Comment by MasonProtter** [comment]
ping @MikeInnes

**Comment by oxinabox** [comment]
This would be cool

**Comment by oxinabox** [comment]
Docstring for `@trace` needs to be updated

**Comment by MasonProtter** [comment]
> Docstring for `@trace` needs to be updated

Good call. Done

**Review by oxinabox — APPROVED** [review]

**Comment by oxinabox** [comment]
@MasonProtter  you now have merge rights on this, and i have reviewed so lets do this

**Comment by MasonProtter** [comment]
I do not appear to have merge rights yet.

**Comment by MasonProtter** [comment]
Pinging @DhairyaLGandhi

**Comment by DhairyaLGandhi** [comment]
Could you check again? You should have an invite

**Comment by DhairyaLGandhi** [comment]
Largely seems to make sense to me. It's an interesting proposition, something I'd like to see in as well

**Comment by oxinabox** [comment]
Going to this page sometimes lets you accept directly IIRC
https://github.com/orgs/FluxML/people

**Comment by DhairyaLGandhi** [comment]
Also - resent the invite

**Comment by MasonProtter** [comment]
There we go, Github did not make it obvious that I had received an invitation.

**Pull request merged**
